export genUID=$(id -u)
export genGID=$(id -g)

export RUST_TEMPLATE_DIR=$HOME/Work/back_end/rust_template

export KUBECONFIG="$HOME/.config/kube/config"

# --- Android SDK (Arch layout) ---
export ANDROID_SDK_ROOT=/opt/android-sdk
export ANDROID_HOME=/opt/android-sdk
export ANDROID_AVD_HOME="$HOME/.android/avd"

# using UV instead of pip for python scripting
export $HOME/.local/share/../bin/env

export PATH="$PATH:\
$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:\
$ANDROID_SDK_ROOT/platform-tools:\
$ANDROID_SDK_ROOT/emulator"

# Flutter has to be run from a local / user because of grable permission issues
export PATH="$HOME/.local/share/flutter/bin:$PATH"

# --- Use JDK 17 for Android builds --- 25 available but 17 is only compatible with Flutter
export JAVA_HOME="/usr/lib/jvm/java-17-openjdk"
export PATH="$JAVA_HOME/bin:$PATH"
export GRADLE_USER_HOME="$HOME/.gradle"
export XDG_DATA_DIRS="/var/lib/flatpak/exports/share:$HOME/.local/share/flatpak/exports/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"

# exports for RUST_TEMPLATE
export RUST_TEMPLATE_DIR="$HOME/Work/back_end/rust_template"
export RUST_OWNER="1000482371 ONTARIO CORPORATION"

# exports for open-code
export LLAMA_CPP_BASE_URL="http://192.168.2.15:8080/v1"
export LLAMA_CPP_API_KEY="not-needed"
export LLAMA_CPP_MODEL="unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q5_K_XL"


export BASH_CUSTOM_DIR="$HOME/.config/bash_custom"

# Optional private overrides
[[ -f "$HOME/.config/bash_custom/private_exports.conf" ]] && \
  source "$HOME/.config/bash_custom/private_exports.conf"
eval "$(fnm env)"
