-- ~/.config/nvim/lua/plugins/opencode.lua

return {
  -- "nickjvandyke/opencode.nvim",
  --
  -- dependencies = {
  --   { "folke/snacks.nvim", opts = { input = {}, picker = {}, terminal = {} } },
  -- },
  --
  -- keys = {
  --   {
  --     "<C-.>",
  --     function()
  --       if vim.g.opencode_open then
  --         -- Try to close
  --         pcall(function() require("opencode").command("close") end)
  --         vim.g.opencode_open = false
  --       else
  --         require("opencode").prompt()
  --         vim.g.opencode_open = true
  --       end
  --     end,
  --     mode = { "n", "t" },
  --     desc = "Opencode Toggle",
  --   },
  -- },
  --
  -- config = function()
  --   vim.g.opencode_opts = {
  --     provider = { enabled = "snacks" },
  --   }
  --   vim.g.opencode_open = false   -- initial state
  --   vim.o.autoread = true
  -- end,
}
